services:
  todo-frontend:
    image: fso-p12-todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./todo-frontend:/app
    ports:
      - 3001:3000
  nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - todo-frontend
