version: '3.9'

services:
  nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - bloglist-frontend
      - bloglist-backend
  bloglist-frontend:
    image: fso-p12-bloglist-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
  bloglist-backend:
    image: fso-p12-bloglist-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
