version: '3.9'

services:
  bloglist-frontend:
    image: fso-p12-bloglist-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - 3004:3004
  bloglist-backend:
    image: fso-p12-bloglist-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - 3003:3003
